# "$schema" = 'https://starship.rs/config-schema.json'
#
# format = """
# [](sumiInk1)\
# $os\
# $username\
# [](bg:surimiOrange fg:sumiInk1)\
# $directory\
# [](fg:surimiOrange bg:springGreen)\
# $git_branch\
# $git_status\
# [](fg:springGreen bg:waveAqua1)\
# $c\
# $rust\
# $golang\
# $nodejs\
# $php\
# $java\
# $kotlin\
# $haskell\
# $python\
# [](fg:waveAqua1 bg:crystalBlue)\
# $docker_context\
# [](fg:crystalBlue bg:oniViolet)\
# $time\
# [ ](fg:oniViolet)\
# $line_break$character"""
#
# # Use the Kanagawa Wave palette
# palette = 'kanagawa_wave'
#
# [palettes.kanagawa_wave]
# fujiWhite = "#dcd7ba"
# sumiInk1 = "#1f1f28"
# sumiInk4 = "#54546d"
# crystalBlue = "#7e9cd8"
# waveAqua1 = "#6a9589"
# springGreen = "#98bb6c"
# surimiOrange = "#ffa066"
# oniViolet = "#957fb8"
# samuraiRed = "#e82424"
# carpYellow = "#e6c384"
#
# [os]
# disabled = false
# style = "bg:sumiInk1 fg:fujiWhite"
#
# [os.symbols]
# Windows = "󰍲"
# Ubuntu = "󰕈"
# SUSE = ""
# Raspbian = "󰐿"
# Mint = "󰣭"
# Macos = "󰀵"
# Manjaro = ""
# Linux = "󰌽"
# Gentoo = "󰣨"
# Fedora = "󰣛"
# Alpine = ""
# Amazon = ""
# Android = ""
# Arch = "󰣇"
# Artix = "󰣇"
# EndeavourOS = ""
# CentOS = ""
# Debian = "󰣚"
# Redhat = "󱄛"
# RedHatEnterprise = "󱄛"
# Pop = ""
#
# [username]
# show_always = true
# style_user = "bg:sumiInk1 fg:fujiWhite"
# style_root = "bg:sumiInk1 fg:fujiWhite"
# format = '[ $user ]($style)'
#
# [directory]
# style = "fg:sumiInk4 bg:surimiOrange"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = "󰝚 "
# "Pictures" = " "
# "Developer" = "󰲋 "
#
# [git_branch]
# symbol = ""
# style = "bg:waveAqua1"
# format = '[[ $symbol $branch ](fg:sumiInk1 bg:springGreen)]($style)'
#
# [git_status]
# style = "bg:waveAqua1"
# format = '[[($all_status$ahead_behind )](fg:sumiInk1 bg:springGreen)]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:waveAqua1"
# format = '[[ $symbol( $version) ](fg:sumiInk1 bg:waveAqua1)]($style)'
#
# [c]
# symbol = " "
# style = "bg:waveAqua1"
# format = '[[ $symbol( $version) ](fg:sumiInk1 bg:waveAqua1)]($style)'
#
# [rust]
# symbol = ""
# style = "bg:waveAqua1"
# format = '[[ $symbol( $version) ](fg:sumiInk1 bg:waveAqua1)]($style)'
#
# [golang]
# symbol = ""
# style = "bg:waveAqua1"
# format = '[[ $symbol( $version) ](fg:sumiInk1 bg:waveAqua1)]($style)'
#
# [php]
# symbol = ""
# style = "bg:waveAqua1"
# format = '[[ $symbol( $version) ](fg:sumiInk1 bg:waveAqua1)]($style)'
#
# [java]
# symbol = ""
# style = "bg:waveAqua1"
# format = '[[ $symbol( $version) ](fg:sumiInk1 bg:waveAqua1)]($style)'
#
# [kotlin]
# symbol = ""
# style = "bg:waveAqua1"
# format = '[[ $symbol( $version) ](fg:sumiInk1 bg:waveAqua1)]($style)'
#
# [haskell]
# symbol = ""
# style = "bg:waveAqua1"
# format = '[[ $symbol( $version) ](fg:sumiInk1 bg:waveAqua1)]($style)'
#
# [python]
# symbol = ""
# style = "bg:waveAqua1"
# format = '[[ $symbol( $version) ](fg:sumiInk1 bg:waveAqua1)]($style)'
#
# [docker_context]
# symbol = ""
# style = "bg:sumiInk4"
# format = '[[ $symbol( $context) ](fg:crystalBlue bg:sumiInk4)]($style)'
#
# [time]
# disabled = false
# time_format = "%R"
# style = "bg:surimiOrange"
# format = '[[  $time ](fg:sumiInk4 bg:oniViolet)]($style)'
#
# [line_break]
# disabled = false
#
# [character]
# disabled = false
# success_symbol = '[](bold fg:springGreen)'
# error_symbol = '[](bold fg:samuraiRed)'
# vimcmd_symbol = '[](bold fg:springGreen)'
# vimcmd_replace_one_symbol = '[](bold fg:oniViolet)'
# vimcmd_replace_symbol = '[](bold fg:oniViolet)'
# vimcmd_visual_symbol = '[](bold fg:carpYellow)'

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
